[llm]
model = "/data/ziyang/models/GLM-4.6-FP8"
custom_llm_provider = "openai"
base_url = "http://127.0.0.1:8000/v1"
api_key = "dummy"
temperature = 1.0
native_tool_calling = false

[llm.vllm_local]
model = "/data/ziyang/models/GLM-4.6-FP8"
custom_llm_provider = "openai"
base_url = "http://127.0.0.1:8000/v1"
api_key = "dummy"
temperature = 1.0
native_tool_calling = false

[sandbox]
rm_all_containers = false
cleanup_runtime_image = false
